### ISSUE TITLE
Discussion: Should attack_info be json?

### ISSUE THREAD

**Issue by domenukk** [enowars/specification#11]
The important part is in the title: should attack_info be a json, instead of a string?
Given that strings are valid json, this leaves us with a good flexibility, and would allow for multiple informations, for example, `{"username": x, "endpoint": y}` or similar.

**Comment by PistonMiner** [comment]
The primary reason I initially proposed a simple string is because I am unsure if the serialization frameworks in use across the various checkers (Python, C#, Rust) and the engine can handle arbitrary JSON easily.

Other points:
* the same complexity concerns may apply to teams' exploit infrastructure
* if one really wants JSON one can always just dump it into a string and return it like that
* it needs to be converted to a string going into the database anyways
* e.g. SaarCTF also seems to just use a single string

In short, it felt like unnecessary complexity to me particularly on the checker side, however I don't feel strongly either way.
I do see the advantage of not having to do some kind of more elaborate parsing on the exploit side, even if it's just unpacking another level of JSON.

The serialization complexity issue could be partially sidestepped by escaping the JSON and then just passing it along as a string like currently, and when the engine generates the public info it can just interpret it as JSON instead, that way you sorta get the best of both worlds but you still have to deal with converting arbitrary stuff to JSON from the checker code. That's probably straightforward enough in Python, I don't know about the other checker frameworks.

**Comment by Trolldemorted** [comment]
I also think leaving this unspecified, and recommending escaped json strings is the easiest way to go.

**Comment by ldruschk** [comment]
> I also think leaving this unspecified, and recommending escaped json strings is the easiest way to go.

What do you mean by leaving this unspecified? We can't just allow everything and expect the engine to handle this properly.

I agree that string values should be sufficient, this also should reduce the complexity in the Engine.

**Comment by Trolldemorted** [comment]
>What do you mean by leaving this unspecified? We can't just allow everything and expect the engine to handle this properly.

*anything string-y, point taken :)

**Comment by domenukk** [comment]
Anything JSON-y would not make the engine more or less complex, but I'll go ahead and close this, then :)
